# Используем официальный образ Python
FROM python:3.12

# Устанавливаем рабочую директорию
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем исходный код
COPY . .


# Команда для запуска Celery worker
CMD ["celery", "-A", "src.celery_repo.celery_config.celery_app", "worker", "--loglevel=info"]

